// <auto-generated />
using System;
using Ecommerce_WatchShop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce_WatchShop.Migrations
{
    [DbContext(typeof(DongHoContext))]
    partial class DongHoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce_WatchShop.Models.BaiViet", b =>
                {
                    b.Property<int>("MaBaiViet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaiViet"));

                    b.Property<string>("HinhAnh")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("TieuDe")
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaBaiViet");

                    b.ToTable("BaiViets");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.BinhLuanSanPham", b =>
                {
                    b.Property<int>("MaBinhLuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBinhLuan"));

                    b.Property<int?>("KhachHangMaKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaBinhLuan");

                    b.HasIndex("KhachHangMaKhachHang");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaSanPham");

                    b.ToTable("BinhLuanSanPhams");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("MaChiTietHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietHoaDon"));

                    b.Property<decimal>("Gia")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTien")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("MaChiTietHoaDon");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaSanPham");

                    b.ToTable("ChiTietHoaDons");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.ChinhSach", b =>
                {
                    b.Property<int>("Ma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ma"));

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ma");

                    b.ToTable("ChinhSachs");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.DanhGiaSanPham", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<int?>("DiemDanhGia")
                        .HasColumnType("int");

                    b.Property<int?>("KhachHangMaKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("KhachHangMaKhachHang");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaSanPham");

                    b.ToTable("DanhGiaSanPhams");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.DanhMuc", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMuc"));

                    b.Property<string>("HinhAnh")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("MaDanhMucCha")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TenDanhMuc")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaDanhMuc");

                    b.ToTable("DanhMucs");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.Footer", b =>
                {
                    b.Property<int>("Ma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ma"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Ma");

                    b.ToTable("Footers");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.FooterLink", b =>
                {
                    b.Property<int>("Ma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ma"));

                    b.Property<int>("MaNhom")
                        .HasColumnType("int");

                    b.Property<int>("ThuTuHienThi")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ma");

                    b.ToTable("FooterLinks");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.GiaTriThuocTinh", b =>
                {
                    b.Property<int>("MaGiaTri")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiaTri"));

                    b.Property<string>("GiaTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaThuocTinh")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ThuTuHienThi")
                        .HasColumnType("int");

                    b.HasKey("MaGiaTri");

                    b.HasIndex("MaThuocTinh");

                    b.ToTable("GiaTriThuocTinhs");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.GioiThieu", b =>
                {
                    b.Property<int>("Ma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ma"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ma");

                    b.ToTable("GioiThieus");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.HinhAnhBaiViet", b =>
                {
                    b.Property<int>("MaHinhAnhBaiViet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHinhAnhBaiViet"));

                    b.Property<int?>("BaiVietMaBaiViet")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaBaiViet")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaHinhAnhBaiViet");

                    b.HasIndex("BaiVietMaBaiViet");

                    b.ToTable("HinhAnhBaiViets");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.HinhAnhSanPham", b =>
                {
                    b.Property<int>("MaHinhAnhSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHinhAnhSanPham"));

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<int?>("SanPhamMaSanPham")
                        .HasColumnType("int");

                    b.HasKey("MaHinhAnhSanPham");

                    b.HasIndex("SanPhamMaSanPham");

                    b.ToTable("HinhAnhSanPhams");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<bool>("DaYeuCauHuy")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Huyen")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("KhachHangMaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDatHang")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayYeuCauHuy")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Tinh")
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<string>("Xa")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("YeuCauHuy")
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("KhachHangMaKhachHang");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.Huyen", b =>
                {
                    b.Property<int>("MaHuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHuyen"));

                    b.Property<int>("MaTinh")
                        .HasColumnType("int");

                    b.Property<string>("TenHuyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaHuyen");

                    b.HasIndex("MaTinh");

                    b.ToTable("Huyens");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MaHuyen")
                        .HasColumnType("int");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<int?>("MaTinh")
                        .HasColumnType("int");

                    b.Property<int?>("MaXa")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TenHienThi")
                        .HasColumnType("varchar(200)");

                    b.HasKey("MaKhachHang");

                    b.HasIndex("MaHuyen");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique()
                        .HasFilter("[MaTaiKhoan] IS NOT NULL");

                    b.HasIndex("MaTinh");

                    b.HasIndex("MaXa");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.LienHe", b =>
                {
                    b.Property<int>("MaLienHe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLienHe"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaLienHe");

                    b.ToTable("LienHes");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.SanPham", b =>
                {
                    b.Property<int>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSanPham"));

                    b.Property<int?>("DaXoa")
                        .HasColumnType("int");

                    b.Property<double>("Gia")
                        .HasColumnType("float");

                    b.Property<double?>("GiaKhuyenMai")
                        .HasColumnType("float");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LuotXem")
                        .HasColumnType("int");

                    b.Property<int>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<int>("MaThuongHieu")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MoTaNgan")
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PhanTramKhuyenMai")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Slug")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ThongSoKyThuat")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaSanPham");

                    b.HasIndex("MaDanhMuc");

                    b.HasIndex("MaThuongHieu");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.SanPhamThuocTinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaGiaTri")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaGiaTri");

                    b.HasIndex("MaSanPham");

                    b.ToTable("SanPhamThuocTinhs");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.Slider", b =>
                {
                    b.Property<int>("Ma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ma"));

                    b.Property<bool>("HienThiTrangChu")
                        .HasColumnType("bit");

                    b.Property<bool>("HienThiTrangSanPham")
                        .HasColumnType("bit");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ThuTuHienThi")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Ma");

                    b.ToTable("Sliders");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<int?>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TenDangNhap")
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("VaiTroMaVaiTro")
                        .HasColumnType("int");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("VaiTroMaVaiTro");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.ThuocTinhSanPham", b =>
                {
                    b.Property<int>("MaThuocTinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThuocTinh"));

                    b.Property<bool>("HienThi")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Slug")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TenThuocTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ThuTuHienThi")
                        .HasColumnType("int");

                    b.HasKey("MaThuocTinh");

                    b.ToTable("ThuocTinhSanPhams");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.ThuongHieu", b =>
                {
                    b.Property<int>("MaThuongHieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThuongHieu"));

                    b.Property<int?>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Slug")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TenThuongHieu")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("varchar(20)");

                    b.HasKey("MaThuongHieu");

                    b.HasIndex("MaDanhMuc");

                    b.ToTable("ThuongHieus");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.Tinh", b =>
                {
                    b.Property<int>("MaTinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTinh"));

                    b.Property<string>("TenTinh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTinh");

                    b.ToTable("Tinhs");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.TokenKhoiPhucMatKhau", b =>
                {
                    b.Property<int>("MaDinhDanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDinhDanh"));

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("MaToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.HasKey("MaDinhDanh");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("TokenKhoiPhucMatKhaus");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("Loai")
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTros");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.Xa", b =>
                {
                    b.Property<int>("MaXa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaXa"));

                    b.Property<int>("MaHuyen")
                        .HasColumnType("int");

                    b.Property<string>("TenXa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaXa");

                    b.HasIndex("MaHuyen");

                    b.ToTable("Xas");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.YeuThich", b =>
                {
                    b.Property<int>("MaYeuThich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaYeuThich"));

                    b.Property<int?>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.HasKey("MaYeuThich");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaSanPham");

                    b.ToTable("YeuThichs");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.BinhLuanSanPham", b =>
                {
                    b.HasOne("Ecommerce_WatchShop.Models.KhachHang", null)
                        .WithMany("ProductComments")
                        .HasForeignKey("KhachHangMaKhachHang");

                    b.HasOne("Ecommerce_WatchShop.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ecommerce_WatchShop.Models.SanPham", "SanPham")
                        .WithMany("BinhLuanSanPhams")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("Ecommerce_WatchShop.Models.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce_WatchShop.Models.SanPham", "SanPham")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.DanhGiaSanPham", b =>
                {
                    b.HasOne("Ecommerce_WatchShop.Models.KhachHang", null)
                        .WithMany("ProductRatings")
                        .HasForeignKey("KhachHangMaKhachHang");

                    b.HasOne("Ecommerce_WatchShop.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ecommerce_WatchShop.Models.SanPham", "SanPham")
                        .WithMany("DanhGiaSanPhams")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.GiaTriThuocTinh", b =>
                {
                    b.HasOne("Ecommerce_WatchShop.Models.ThuocTinhSanPham", "ThuocTinh")
                        .WithMany("GiaTriThuocTinhs")
                        .HasForeignKey("MaThuocTinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThuocTinh");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.HinhAnhBaiViet", b =>
                {
                    b.HasOne("Ecommerce_WatchShop.Models.BaiViet", "BaiViet")
                        .WithMany("HinhAnhBaiViets")
                        .HasForeignKey("BaiVietMaBaiViet");

                    b.Navigation("BaiViet");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.HinhAnhSanPham", b =>
                {
                    b.HasOne("Ecommerce_WatchShop.Models.SanPham", "SanPham")
                        .WithMany("HinhAnhSanPhams")
                        .HasForeignKey("SanPhamMaSanPham");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.HoaDon", b =>
                {
                    b.HasOne("Ecommerce_WatchShop.Models.KhachHang", "KhachHang")
                        .WithMany("Bills")
                        .HasForeignKey("KhachHangMaKhachHang");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.Huyen", b =>
                {
                    b.HasOne("Ecommerce_WatchShop.Models.Tinh", "Tinh")
                        .WithMany("Huyens")
                        .HasForeignKey("MaTinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tinh");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.KhachHang", b =>
                {
                    b.HasOne("Ecommerce_WatchShop.Models.Huyen", "Huyen")
                        .WithMany()
                        .HasForeignKey("MaHuyen")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ecommerce_WatchShop.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("KhachHang")
                        .HasForeignKey("Ecommerce_WatchShop.Models.KhachHang", "MaTaiKhoan");

                    b.HasOne("Ecommerce_WatchShop.Models.Tinh", "Tinh")
                        .WithMany()
                        .HasForeignKey("MaTinh")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ecommerce_WatchShop.Models.Xa", "Xa")
                        .WithMany()
                        .HasForeignKey("MaXa")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Huyen");

                    b.Navigation("TaiKhoan");

                    b.Navigation("Tinh");

                    b.Navigation("Xa");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.SanPham", b =>
                {
                    b.HasOne("Ecommerce_WatchShop.Models.DanhMuc", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce_WatchShop.Models.ThuongHieu", "ThuongHieu")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaThuongHieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");

                    b.Navigation("ThuongHieu");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.SanPhamThuocTinh", b =>
                {
                    b.HasOne("Ecommerce_WatchShop.Models.GiaTriThuocTinh", "GiaTriThuocTinh")
                        .WithMany("SanPhamThuocTinhs")
                        .HasForeignKey("MaGiaTri")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce_WatchShop.Models.SanPham", "SanPham")
                        .WithMany("SanPhamThuocTinhs")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaTriThuocTinh");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.TaiKhoan", b =>
                {
                    b.HasOne("Ecommerce_WatchShop.Models.VaiTro", "VaiTro")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("VaiTroMaVaiTro");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.ThuongHieu", b =>
                {
                    b.HasOne("Ecommerce_WatchShop.Models.DanhMuc", "DanhMuc")
                        .WithMany()
                        .HasForeignKey("MaDanhMuc");

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.TokenKhoiPhucMatKhau", b =>
                {
                    b.HasOne("Ecommerce_WatchShop.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.Xa", b =>
                {
                    b.HasOne("Ecommerce_WatchShop.Models.Huyen", "Huyen")
                        .WithMany("Xas")
                        .HasForeignKey("MaHuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Huyen");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.YeuThich", b =>
                {
                    b.HasOne("Ecommerce_WatchShop.Models.KhachHang", "KhachHang")
                        .WithMany("YeuThichs")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ecommerce_WatchShop.Models.SanPham", "SanPham")
                        .WithMany("YeuThichs")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.BaiViet", b =>
                {
                    b.Navigation("HinhAnhBaiViets");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.GiaTriThuocTinh", b =>
                {
                    b.Navigation("SanPhamThuocTinhs");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.Huyen", b =>
                {
                    b.Navigation("Xas");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.KhachHang", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("ProductComments");

                    b.Navigation("ProductRatings");

                    b.Navigation("YeuThichs");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.SanPham", b =>
                {
                    b.Navigation("BinhLuanSanPhams");

                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("DanhGiaSanPhams");

                    b.Navigation("HinhAnhSanPhams");

                    b.Navigation("SanPhamThuocTinhs");

                    b.Navigation("YeuThichs");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.TaiKhoan", b =>
                {
                    b.Navigation("KhachHang")
                        .IsRequired();
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.ThuocTinhSanPham", b =>
                {
                    b.Navigation("GiaTriThuocTinhs");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.ThuongHieu", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.Tinh", b =>
                {
                    b.Navigation("Huyens");
                });

            modelBuilder.Entity("Ecommerce_WatchShop.Models.VaiTro", b =>
                {
                    b.Navigation("TaiKhoans");
                });
#pragma warning restore 612, 618
        }
    }
}
